### ISSUE TITLE
help

### ISSUE THREAD

**Issue by heraldo1980** [higan-emu/bahamut-lagoon-translation-kit#1]
friend, I don't have much experience in programming, you could give me this bildada tool, of course, only if you can.

**Comment by Screwtapello** [comment]
I'm afraid there are no pre-built versions of the Translation Kit, you'll need to build it yourself (or find somebody with more programming experience to build it for you). Almost all the instructions that exist are in [the README file](https://github.com/higan-emu/bahamut-lagoon-translation-kit#readme), although if you're on Windows and need MSYS2 you can find a few more details about that [in higan's documentation](https://github.com/higan-emu/higan/wiki/Building-on-Windows#setup).

If you get stuck or have further questions, you can drop by [the bsnes Discord chat](https://discord.gg/xdsQRXfuCh) and hopefully somebody there will be able to answer your questions.
